import type { NextPage } from 'next';
import Head from 'next/head';
import Counter from 'components/counter/Counter';
import { Button } from '@mui/material';

const Home: NextPage = () => {
	return (
		<>
			<Head>
				<title>eLMS App</title>
				<meta
					name='description'
					content='Generated by create next app'
				/>
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<Counter />
			<Button size='large' color='primary' variant='outlined'>
				Test Button
			</Button>
		</>
	);
};

export default Home;
